import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import CartIcon from "./components/CartIcon";
import { AuthButton } from "./components/AuthButton";

// GEIST (variable font)
const geist = localFont({
  src: [
    { path: "../public/fonts/geist/Geist-wght.woff2", style: "normal" },
    { path: "../public/fonts/geist/Geist-Italic-wght.woff2", style: "italic" },
  ],
  variable: "--font-geist",
});

// GEIST MONO (variable font)
const geistMono = localFont({
  src: [
    { path: "../public/fonts/geist-mono/GeistMono-wght.woff2", style: "normal" },
    { path: "../public/fonts/geist-mono/GeistMono-Italic-wght.woff2", style: "italic" },
  ],
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="es"
      className={`${geist.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        {/* HEADER GLOBAL */}
        <header className="w-full bg-white/70 backdrop-blur-md shadow-sm py-3 px-4 flex items-center justify-between sticky top-0 z-50">

          <a
            href="/"
            className="text-green-700 hover:text-green-900 font-semibold text-lg sm:text-xl whitespace-nowrap"

          >
            ← Pagina principal
          </a>

          <div className="flex items-center gap-2 sm:gap-3">
            <a
              href="/carrito"
              className="text-black-700 hover:text-green-900 font-semibold text-lg sm:text-xl whitespace-nowrap"
              >
              Carrito
            </a>

            <CartIcon />
            
            <AuthButton />
          </div>
        </header>

        {children}

      </body>
    </html>
  );
}