import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header";

// GEIST (variable font)
const geist = localFont({
  src: [
    { path: "../public/fonts/geist/Geist-wght.woff2", style: "normal" },
    { path: "../public/fonts/geist/Geist-Italic-wght.woff2", style: "italic" },
  ],
  variable: "--font-geist",
});

// GEIST MONO (variable font)
const geistMono = localFont({
  src: [
    { path: "../public/fonts/geist-mono/GeistMono-wght.woff2", style: "normal" },
    { path: "../public/fonts/geist-mono/GeistMono-Italic-wght.woff2", style: "italic" },
  ],
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="es"
      className={`${geist.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header />
        {children}
      </body>
    </html>
  );
}